language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "nightly"

dist: trusty
sudo: required

addons:
  apt:
    packages:
    - build-essential

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq gcc-6
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90
    - git submodule init
    - git submodule update
    - pip install -r requirements.txt
    - pip install .

script:
    - flake8 yoga test
    - pytest -v test

