language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "nightly"

dist: trusty
sudo: required

addons:
  apt:
    packages:
    - build-essential

install:
    - git submodule init
    - git submodule update
    - pip install -r requirements.txt
    - pip install .

script:
    - flake8 yoga test
    - pytest -v

